# fly.toml app configuration file generated for node-code-challenge on 2023-09-04T14:35:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-code-challenge"
primary_region = "qro"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
